INSERT INTO `product_ingredients` (`product_id`, `ingredients`) VALUES
(52765,'Enchilada sauce,shredded Monterey Jack cheese,corn tortillas,chicken breasts,null,null'),
(52767,'plain flour,chilled butter,cold water,raspberry jam,butter,caster sugar'),
(52768,'digestive biscuits,butter,Bramley apples,Salted Butter,caster sugar,free-range eggs, beaten'),
(52770,'onions,olive oil,garlic,lean minced beef,mushrooms,dried oregano'),
(52771,'penne rigate,olive oil,garlic,chopped tomatoes,red chilli flakes,italian seasoning'),
(52772,'soy sauce,water,brown sugar,ground ginger,minced garlic,cornstarch'),
(52774,'rice stick noodles,dark soy sauce,oyster sauce,soy sauce,white vinegar,sugar'),
(52776,'Plain chocolate,Butter,Milk,Eggs,Granulated Sugar,Flour'),
(52780,'Potatoes,Onions,Olive Oil,Chicken Stock,Creme Fraiche,Parmesan'),
(52781,'whole wheat,lamb loin chops,olive oil,shallots,Carrots,turnips'),
(52784,'Olive Oil,Onion,Leek,Garlic,Cumin,Coriander'),
(52785,'Toor dal,Water,Salt,Turmeric,Ghee,Chopped tomatoes'),
(52786,'Miniature Marshmallows,Chocolate Chips,Peanut Butter,Vanilla Extract,Peanuts,'),
(52787,'Chocolate Chips,Heavy Cream,Condensed Milk,Vanilla Extract,White Chocolate Chips,Miniature Marshmallows'),
(52788,'salted butter,dark soft brown sugar,golden syrup,orange,rolled oats,Christmas pudding'),
(52791,'strawberries,double cream,meringue nests,ginger cordial,Mint,'),
(52792,'butter,bread,sultanas,cinnamon,milk,double cream'),
(52793,'Medjool dates,water,vanilla extract,self-raising flour,bicarbonate of soda,eggs'),
(52795,'Chicken,Onion,Tomatoes,Garlic,Ginger paste,Vegetable oil'),
(52796,'Butter,Olive Oil,Chicken,Salt,Squash,Broccoli'),
(52797,'Small Potatoes,Harissa Spice,olive oil,Lemon,Spring onions,Rocket'),
(52803,'mushrooms,English Mustard,Olive Oil,Beef Fillet,Parma ham,Puff Pastry'),
(52806,'lemons,paprika,red onions,chicken thighs,vegetable oil,Greek yogurt'),
(52807,'Aubergine,Onion,Tomatoes,Garlic,Green Chilli,Red Chilli Powder'),
(52811,'Olive Oil,Onion,Carrots,Celery,Garlic,Cannellini Beans'),
(52812,'Beef Brisket,Salt,Onion,Garlic,Thyme,Rosemary'),
(52813,'Chicken,Oil,Egg White,Flour,Brown Sugar,Salt'),
(52814,'Potatoes,green beans,sunflower oil,garlic,Thai green curry paste,coconut milk'),
(52816,'Olive Oil,Carrots,Celery,Onion,Garlic,Brown Lentils'),
(52817,'Olive Oil,Egg Plants,Harissa Spice,Chickpeas,Cherry Tomatoes,Greek yogurt'),
(52818,'macaroni,chicken stock,heavy cream,fajita seasoning,salt,chicken breast'),
(52820,'chicken breast,plain flour,egg,breadcrumbs,vegetable oil,sunflower oil'),
(52824,'Beef,Broccoli,Potatoes,Carrots,plain flour,Eggs'),
(52826,'Beef,Onions,Garlic,Olive oil,Chorizo,Cumin'),
(52827,'Peanuts,Coconut cream,Massaman curry paste,Beef,Potatoes,Onion'),
(52829,'Macaroni,Plain Flour,Mustard Powder,Garlic powder,Kosher salt,Black pepper'),
(52830,'Chicken Breasts,Vinaigrette Dressing,Cumin,Smoked Paprika,Garlic,Refried Beans'),
(52831,'Chicken,Ginger,Garlic,Soy sauce,Sake,Granulated sugar'),
(52832,'Olive Oil,Bacon,Shallots,Chicken Legs,Chicken Thighs,Chicken Breasts'),
(52833,'Digestive Biscuits,Pretzels,Butter,Cream Cheese,Vanilla Extract,Icing Sugar'),
(52834,'Olive Oil,Onions,Garlic,Butter,Mushrooms,Beef Fillet'),
(52835,'Clotted Cream,Butter,Corn Flour,Parmesan Cheese,Nutmeg,Fettuccine'),
(52837,'Spaghetti,Olive Oil,Onion,Garlic,Red Chilli,Tomato Puree'),
(52838,'Olive Oil,Duck Legs,Onions,Garlic,Cinnamon,Plain Flour'),
(52839,'Linguine Pasta,Sugar Snap Peas,Olive Oil,Garlic Clove,Red Chilli,King Prawns'),
(52844,'Olive Oil,Bacon,Onion,Celery,Carrots,Garlic'),
(52846,'Butter,Onion,Mushrooms,Plain Flour,Chicken Stock Cube,Nutmeg'),
(52849,'Olive Oil,Garlic,Caster Sugar,Red Wine Vinegar,Chopped Tomatoes,Basil Leaves'),
(52850,'Olive Oil,Onion,Chicken Breast,Ginger,Harissa Spice,Dried Apricots'),
(52851,'Red Chilli,Ginger,Garlic,Coriander,Sunflower Oil,Chicken Breasts'),
(52853,'Banana,Cacao,Avocado,Honey,Lemon Juice,Vanilla'),
(52854,'Flour,Eggs,Milk,Sunflower Oil,Sugar,Raspberries'),
(52855,'Banana,Eggs,Baking Powder,Vanilla Extract,Oil,Pecan Nuts'),
(52856,'Plain Flour,Butter,Cream Cheese,Icing Sugar,Butter,Maple Syrup'),
(52857,'Pumpkin,Shortcrust Pastry,Plain Flour,Caster Sugar,Salt,Nutmeg'),
(52858,'Butter,Sour Cream,Sugar,Cream Cheese,Caster Sugar,Plain Flour'),
(52859,'Digestive Biscuits,Butter,Condensed Milk,Egg Yolks,Lime,Double Cream'),
(52860,'Dark Chocolate,Milk Chocolate,Salted Butter,Light Brown Soft Sugar,Eggs,Plain Flour'),
(52861,'Butter,Peanut Cookies,Gelatine Leafs,Ricotta,Peanut Butter,Golden Syrup'),
(52862,'Corn Flour,Orange,Orange,Caster Sugar,Peaches,Blueberries'),
(52863,'Rapeseed Oil,Onion,Garlic,Paprika,Cumin,Thyme'),
(52864,'Mushrooms,Chestnuts,Challots,Garlic,Rosemary,Wild Mushrooms'),
(52865,'Sunflower Oil,Paneer,Ginger,Cumin,Turmeric,Coriander'),
(52866,'Butternut Squash,Garlic,Olive Oil,Linguine Pasta,Sage,'),
(52867,'Roasted Vegetables,Kidney Beans,Chopped Tomatoes,Mixed Grain,,'),
(52868,'Vegetable Oil,Onion,Garlic,Ginger,Coriander,Cumin'),
(52869,'Tahini,Lemon,Olive Oil,Red Onions,Garlic,Yellow Pepper'),
(52870,'Chickpeas,Olive Oil,Paprika,Tomatoes,Red Onions,Red Wine Vinegar'),
(52871,'Udon Noodles,Sesame Seed Oil,Onion,Cabbage,Shiitake Mushrooms,Spring Onions'),
(52872,'Onion,Olive Oil,Butter,Potatoes,Garlic,Eggs'),
(52873,'Olive Oil,Butter,Beef,Plain Flour,Garlic,Onions'),
(52874,'Beef,Plain Flour,Rapeseed Oil,Red Wine,Beef Stock,Onion'),
(52875,'Chicken Stock,Chicken Breast,Butter,Leek,Garlic,Plain Flour'),
(52876,'Vegetable Oil,Minced Beef,Onion,Tomato Puree,Plain Flour,Mushrooms'),
(52878,'Beef,Olive Oil,Shallots,Garlic,Bacon,Thyme'),
(52879,'Potatoes,Butter,Double Cream,Egg Yolks,Butter,Shallots'),
(52881,'Puff Pastry,Egg White,Egg Yolks,Vegetable Oil,Beef,Lamb Kidney'),
(52883,'Butter,Muscovado Sugar,Eggs,Self-raising Flour,Baking Powder,Bicarbonate Of Soda'),
(52886,'Self-raising Flour,Salt,Suet,Currants,Caster Sugar,Lemon'),
(52888,'Butter,Plain Flour,Lemon,Butter,Currants,Mixed Peel'),
(52889,'Strawberries,Blackberries,Redcurrants,Raspberries,Caster Sugar,Bread'),
(52890,'Butter,Self-raising Flour,Vanilla,Suet,Milk,Raspberry Jam'),
(52891,'Hazlenuts,Butter,Caster Sugar,Lemon,Plain Flour,Baking Powder'),
(52892,'Plain Flour,Butter,Golden Syrup,Breadcrumbs,Lemons,Eggs'),
(52893,'Plain Flour,Caster Sugar,Butter,Braeburn Apples,Butter,Demerara Sugar'),
(52894,'Butter,Caster Sugar,Self-raising Flour,Almonds,Baking Powder,Eggs'),
(52895,'Sausages,Bacon,Mushrooms,Tomatoes,Black Pudding,Eggs'),
(52896,'Sausages,Bacon,Mushrooms,Tomatoes,Black Pudding,Eggs'),
(52897,'Vegetable Oil,Plain Flour,Bicarbonate Of Soda,Sugar,Eggs,Salt'),
(52898,'White Flour,Salt,Yeast,Milk,Butter,Eggs'),
(52899,'Almonds,Butter,Muscovado Sugar,Orange,Apricot Jam,Plain Flour'),
(52900,'Butter,Caster Sugar,Eggs,Self-raising Flour,Milk,Lemon'),
(52901,'Self-raising Flour,Caster Sugar,Baking Powder,Butter,Dried Fruit,Eggs'),
(52902,'Butter,Egg,Milk,Golden Syrup,Black Treacle,Brown Sugar'),
(52903,'Butter,Olive Oil,Onion,Sugar,Garlic Clove,Plain Flour'),
(52904,'Goose Fat,Beef Shin,Bacon,Challots,Chestnut Mushroom,Garlic Clove'),
(52905,'Single Cream,Caster Sugar,Dark Chocolate,Butter,Butter,Caster Sugar'),
(52906,'Butter,Leek,Salt,Creme Fraiche,Egg,Egg Yolks'),
(52908,'Aubergine,Courgettes,Yellow Pepper,Tomato,Olive Oil,Basil');