INSERT INTO `product_ingredients` (`product_id`, `ingredients`) VALUES
(52765,'Enchilada sauce,shredded Monterey Jack cheese,corn tortillas,chicken breasts,null,null'),
(52767,'plain flour,chilled butter,cold water,raspberry jam,butter,caster sugar'),
(52768,'digestive biscuits,butter,Bramley apples,Salted Butter,caster sugar,free-range eggs, beaten'),
(52770,'onions,olive oil,garlic,lean minced beef,mushrooms,dried oregano'),
(52771,'penne rigate,olive oil,garlic,chopped tomatoes,red chilli flakes,italian seasoning'),
(52772,'soy sauce,water,brown sugar,ground ginger,minced garlic,cornstarch'),
(52774,'rice stick noodles,dark soy sauce,oyster sauce,soy sauce,white vinegar,sugar'),
(52776,'Plain chocolate,Butter,Milk,Eggs,Granulated Sugar,Flour'),
(52780,'Potatoes,Onions,Olive Oil,Chicken Stock,Creme Fraiche,Parmesan'),
(52781,'whole wheat,lamb loin chops,olive oil,shallots,Carrots,turnips'),
(52784,'Olive Oil,Onion,Leek,Garlic,Cumin,Coriander'),
(52785,'Toor dal,Water,Salt,Turmeric,Ghee,Chopped tomatoes'),
(52786,'Miniature Marshmallows,Chocolate Chips,Peanut Butter,Vanilla Extract,Peanuts,'),
(52787,'Chocolate Chips,Heavy Cream,Condensed Milk,Vanilla Extract,White Chocolate Chips,Miniature Marshmallows'),
(52788,'salted butter,dark soft brown sugar,golden syrup,orange,rolled oats,Christmas pudding'),
(52791,'strawberries,double cream,meringue nests,ginger cordial,Mint,'),
(52792,'butter,bread,sultanas,cinnamon,milk,double cream'),
(52793,'Medjool dates,water,vanilla extract,self-raising flour,bicarbonate of soda,eggs'),
(52795,'Chicken,Onion,Tomatoes,Garlic,Ginger paste,Vegetable oil'),
(52796,'Butter,Olive Oil,Chicken,Salt,Squash,Broccoli'),
(52797,'Small Potatoes,Harissa Spice,olive oil,Lemon,Spring onions,Rocket'),
(52803,'mushrooms,English Mustard,Olive Oil,Beef Fillet,Parma ham,Puff Pastry'),
(52806,'lemons,paprika,red onions,chicken thighs,vegetable oil,Greek yogurt'),
(52807,'Aubergine,Onion,Tomatoes,Garlic,Green Chilli,Red Chilli Powder'),
(52811,'Olive Oil,Onion,Carrots,Celery,Garlic,Cannellini Beans'),
(52812,'Beef Brisket,Salt,Onion,Garlic,Thyme,Rosemary'),
(52813,'Chicken,Oil,Egg White,Flour,Brown Sugar,Salt'),
(52814,'Potatoes,green beans,sunflower oil,garlic,Thai green curry paste,coconut milk'),
(52816,'Olive Oil,Carrots,Celery,Onion,Garlic,Brown Lentils'),
(52817,'Olive Oil,Egg Plants,Harissa Spice,Chickpeas,Cherry Tomatoes,Greek yogurt'),
(52818,'macaroni,chicken stock,heavy cream,fajita seasoning,salt,chicken breast'),
(52820,'chicken breast,plain flour,egg,breadcrumbs,vegetable oil,sunflower oil'),
(52824,'Beef,Broccoli,Potatoes,Carrots,plain flour,Eggs'),
(52826,'Beef,Onions,Garlic,Olive oil,Chorizo,Cumin'),
(52827,'Peanuts,Coconut cream,Massaman curry paste,Beef,Potatoes,Onion'),
(52829,'Macaroni,Plain Flour,Mustard Powder,Garlic powder,Kosher salt,Black pepper'),
(52830,'Chicken Breasts,Vinaigrette Dressing,Cumin,Smoked Paprika,Garlic,Refried Beans'),
(52831,'Chicken,Ginger,Garlic,Soy sauce,Sake,Granulated sugar'),
(52832,'Olive Oil,Bacon,Shallots,Chicken Legs,Chicken Thighs,Chicken Breasts'),
(52833,'Digestive Biscuits,Pretzels,Butter,Cream Cheese,Vanilla Extract,Icing Sugar'),
(52834,'Olive Oil,Onions,Garlic,Butter,Mushrooms,Beef Fillet'),
(52835,'Clotted Cream,Butter,Corn Flour,Parmesan Cheese,Nutmeg,Fettuccine'),
(52837,'Spaghetti,Olive Oil,Onion,Garlic,Red Chilli,Tomato Puree'),
(52838,'Olive Oil,Duck Legs,Onions,Garlic,Cinnamon,Plain Flour'),
(52839,'Linguine Pasta,Sugar Snap Peas,Olive Oil,Garlic Clove,Red Chilli,King Prawns'),
(52844,'Olive Oil,Bacon,Onion,Celery,Carrots,Garlic'),
(52846,'Butter,Onion,Mushrooms,Plain Flour,Chicken Stock Cube,Nutmeg'),
(52849,'Olive Oil,Garlic,Caster Sugar,Red Wine Vinegar,Chopped Tomatoes,Basil Leaves'),
(52850,'Olive Oil,Onion,Chicken Breast,Ginger,Harissa Spice,Dried Apricots'),
(52851,'Red Chilli,Ginger,Garlic,Coriander,Sunflower Oil,Chicken Breasts'),
(52853,'Banana,Cacao,Avocado,Honey,Lemon Juice,Vanilla'),
(52854,'Flour,Eggs,Milk,Sunflower Oil,Sugar,Raspberries'),
(52855,'Banana,Eggs,Baking Powder,Vanilla Extract,Oil,Pecan Nuts'),
(52856,'Plain Flour,Butter,Cream Cheese,Icing Sugar,Butter,Maple Syrup'),
(52857,'Pumpkin,Shortcrust Pastry,Plain Flour,Caster Sugar,Salt,Nutmeg'),
(52858,'Butter,Sour Cream,Sugar,Cream Cheese,Caster Sugar,Plain Flour'),
(52859,'Digestive Biscuits,Butter,Condensed Milk,Egg Yolks,Lime,Double Cream'),
(52860,'Dark Chocolate,Milk Chocolate,Salted Butter,Light Brown Soft Sugar,Eggs,Plain Flour'),
(52861,'Butter,Peanut Cookies,Gelatine Leafs,Ricotta,Peanut Butter,Golden Syrup'),
(52862,'Corn Flour,Orange,Orange,Caster Sugar,Peaches,Blueberries'),
(52863,'Rapeseed Oil,Onion,Garlic,Paprika,Cumin,Thyme'),
(52864,'Mushrooms,Chestnuts,Challots,Garlic,Rosemary,Wild Mushrooms'),
(52865,'Sunflower Oil,Paneer,Ginger,Cumin,Turmeric,Coriander'),
(52866,'Butternut Squash,Garlic,Olive Oil,Linguine Pasta,Sage,'),
(52867,'Roasted Vegetables,Kidney Beans,Chopped Tomatoes,Mixed Grain,,'),
(52868,'Vegetable Oil,Onion,Garlic,Ginger,Coriander,Cumin'),
(52869,'Tahini,Lemon,Olive Oil,Red Onions,Garlic,Yellow Pepper'),
(52870,'Chickpeas,Olive Oil,Paprika,Tomatoes,Red Onions,Red Wine Vinegar'),
(52871,'Udon Noodles,Sesame Seed Oil,Onion,Cabbage,Shiitake Mushrooms,Spring Onions'),
(52872,'Onion,Olive Oil,Butter,Potatoes,Garlic,Eggs'),
(52873,'Olive Oil,Butter,Beef,Plain Flour,Garlic,Onions'),
(52874,'Beef,Plain Flour,Rapeseed Oil,Red Wine,Beef Stock,Onion'),
(52875,'Chicken Stock,Chicken Breast,Butter,Leek,Garlic,Plain Flour'),
(52876,'Vegetable Oil,Minced Beef,Onion,Tomato Puree,Plain Flour,Mushrooms'),
(52878,'Beef,Olive Oil,Shallots,Garlic,Bacon,Thyme'),
(52879,'Potatoes,Butter,Double Cream,Egg Yolks,Butter,Shallots'),
(52881,'Puff Pastry,Egg White,Egg Yolks,Vegetable Oil,Beef,Lamb Kidney'),
(52883,'Butter,Muscovado Sugar,Eggs,Self-raising Flour,Baking Powder,Bicarbonate Of Soda'),
(52886,'Self-raising Flour,Salt,Suet,Currants,Caster Sugar,Lemon'),
(52888,'Butter,Plain Flour,Lemon,Butter,Currants,Mixed Peel'),
(52889,'Strawberries,Blackberries,Redcurrants,Raspberries,Caster Sugar,Bread'),
(52890,'Butter,Self-raising Flour,Vanilla,Suet,Milk,Raspberry Jam'),
(52891,'Hazlenuts,Butter,Caster Sugar,Lemon,Plain Flour,Baking Powder'),
(52892,'Plain Flour,Butter,Golden Syrup,Breadcrumbs,Lemons,Eggs'),
(52893,'Plain Flour,Caster Sugar,Butter,Braeburn Apples,Butter,Demerara Sugar'),
(52894,'Butter,Caster Sugar,Self-raising Flour,Almonds,Baking Powder,Eggs'),
(52895,'Sausages,Bacon,Mushrooms,Tomatoes,Black Pudding,Eggs'),
(52896,'Sausages,Bacon,Mushrooms,Tomatoes,Black Pudding,Eggs'),
(52897,'Vegetable Oil,Plain Flour,Bicarbonate Of Soda,Sugar,Eggs,Salt'),
(52898,'White Flour,Salt,Yeast,Milk,Butter,Eggs'),
(52899,'Almonds,Butter,Muscovado Sugar,Orange,Apricot Jam,Plain Flour'),
(52900,'Butter,Caster Sugar,Eggs,Self-raising Flour,Milk,Lemon'),
(52901,'Self-raising Flour,Caster Sugar,Baking Powder,Butter,Dried Fruit,Eggs'),
(52902,'Butter,Egg,Milk,Golden Syrup,Black Treacle,Brown Sugar'),
(52903,'Butter,Olive Oil,Onion,Sugar,Garlic Clove,Plain Flour'),
(52904,'Goose Fat,Beef Shin,Bacon,Challots,Chestnut Mushroom,Garlic Clove'),
(52905,'Single Cream,Caster Sugar,Dark Chocolate,Butter,Butter,Caster Sugar'),
(52906,'Butter,Leek,Salt,Creme Fraiche,Egg,Egg Yolks'),
(52908,'Aubergine,Courgettes,Yellow Pepper,Tomato,Olive Oil,Basil'),
(52909,'Puff Pastry,Plain Flour,Braeburn Apples,Caster Sugar,Butter,Creme Fraiche'),
(52910,'Puff Pastry,Dark Brown Soft Sugar,Braeburn Apples,Red Wine Jelly,Creme Fraiche,Icing Sugar'),
(52911,'Rapeseed Oil,Leek,Courgettes,Vegetable Stock,Cannellini Beans,Green Beans'),
(52913,'Plain Flour,Caster Sugar,Yeast,Milk,Eggs,Eggs'),
(52914,'Onions,Thyme,Olive Oil,Potatoes,Vegetable Stock,'),
(52916,'Pears,Caster Sugar,Butter,Star Anise,Cardamom,Cinnamon'),
(52917,'Double Cream,White Chocolate Chips,Vanilla,Egg Yolks,Caster Sugar,Caster Sugar'),
(52919,'Potatoes,Fennel,Garlic,Milk,Double Cream,Butter'),
(52920,'Olive Oil,Mushrooms,Chicken Legs,Passata,Chicken Stock Cube,Black Olives'),
(52921,'Eggs,Olive Oil,Courgettes,Spring Onions,Red Pepper,Garlic Clove'),
(52922,'Tiger Prawns,Olive Oil,Onion,Fennel,Carrots,Dry White Wine'),
(52923,'Shortcrust Pastry,Eggs,Muscovado Sugar,Raisins,Vanilla Extract,Butter'),
(52924,'Custard,Caster Sugar,Cocoa,Egg,Digestive Biscuits,Desiccated Coconut'),
(52925,'Ham,Peas,Onions,Carrots,Bay Leaves,Celery'),
(52927,'Beef Brisket,Salt,Black Pepper,Coriander,Sugar,Bay Leaf'),
(52928,'Water,Yeast,Sugar,Milk,Butter,Eggs'),
(52929,'Flour,Sugar,Baking Powder,Salt,Egg,Milk'),
(52930,'Potatoes,Butter,Milk,Minced Beef,Onion,Creamed Corn'),
(52931,'Brown Sugar,Butter,Eggs,Vanilla Extract,Salt,Plain Flour'),
(52932,'Butter,Sugar,Eggs,Vanilla Extract,Flour,Baking Powder'),
(52933,'Butter,Onions,Chicken Stock,Chicken Breast,Potatoes,Salt'),
(52934,'Chicken,Butter,Olive Oil,Red Onions,Red Pepper,Chorizo'),
(52935,'Canola Oil,Beef Fillet,Beef Stock,Butter,Garlic,Challots'),
(52937,'Chicken Thighs,Lime,Spring Onions,Ginger,Garlic,Onion'),
(52938,'Plain Flour,Salt,Curry Powder,Butter,Water,Minced Beef'),
(52940,'Chicken,Tomato,Onions,Garlic Clove,Red Pepper,Carrots'),
(52941,'Kidney Beans,Carrots,Spring Onions,Thyme,Onion,Black Pepper'),
(52943,'Oxtail,Onion,Spring Onions,Garlic,Ginger,Scotch Bonnet'),
(52945,'Sake,Soy Sauce,Sesame Seed Oil,Corn Flour,Water,Chicken'),
(52947,'Tofu,Minced Beef,Sesame Seed Oil,Doubanjiang,Fermented Black Beans,Pepper'),
(52950,'Beef,Salt,Sesame Seed Oil,Pepper,Egg White,Starch'),
(52951,'Chicken Breast,Plain Flour,Egg,Starch,Baking Powder,Salt'),
(52952,'Beef,Salt,Pepper,Sesame Seed Oil,Egg,Starch'),
(52955,'Chicken Stock,Salt,Sugar,Pepper,Sesame Seed Oil,Peas'),
(52956,'Chicken,Salt,Pepper,Ginger Cordial,Ginger,Spring Onions'),
(52957,'Cream Cheese,Sugar,Vanilla Extract,Flour,Puff Pastry,Strawberries'),
(52958,'Peanut Butter,Sugar,Egg,,,'),
(52961,'Ricotta,Eggs,Flour,Sugar,Cinnamon,Lemons'),
(52962,'Eggs,White Wine Vinegar,English Muffins,Butter,Smoked Salmon,Lemon Juice'),
(52963,'Olive Oil,Red Onions,Red Chilli,Garlic,Coriander,Cherry Tomatoes'),
(52964,'Butter,Onion,Cardamom,Turmeric,Cinnamon Stick,Bay Leaf'),
(52965,'Potatoes,Olive Oil,Bacon,Garlic Clove,Maple Syrup,Parsley'),
(52966,'Mars Bar,Butter,Rice Krispies,Milk Chocolate,,'),
(52967,'Self-raising Flour,Sugar,Eggs,Milk,,'),
(52970,'Orange,Caster Sugar,Olive Oil,Flour,Baking Powder,Eggs'),
(52971,'Potatoes,Olive Oil,Green Pepper,Onions,Ras el hanout,Pumpkin'),
(52973,'Olive Oil,Onion,Chickpeas,Vegetable Stock,Cumin,Garlic'),
(52976,'Cashew Nuts,Icing Sugar,Egg Yolks,Orange Blossom Water,Icing Sugar,Almonds'),
(52977,'Lentils,Onion,Carrots,Tomato Puree,Cumin,Paprika'),
(52978,'Potatoes,Butter,Cheese,Onion,Red Pepper,Red Chilli Flakes'),
(52979,'Butter,Flour,Beef Stock,Onion,Parsley,Beef'),
(52981,'Water,Peas,Pork,Vegetable Stock Cube,Celery,Carrots'),
(52982,'Spaghetti,Egg Yolks,Salt,Bacon,Pecorino,Black Pepper'),
(52987,'Sour Cream,Chopped Onion,Dried Oregano,Salt,Bread,Bacon'),
(52988,'Almonds,Bramley Apples,Candied Peel,Nutmeg,Raisins,Plain Flour'),
(52989,'Orange,Demerara Sugar,Grand Marnier,Christmas Pudding,Custard,Mascarpone'),
(52990,'Butter,Muscovado Sugar,Plain Flour,Eggs,Ground Almonds,Sherry'),
(52991,'Butter,Plain Flour,Caster Sugar,Mincemeat,Egg,Icing Sugar'),
(52992,'Potatoes,Carrots,Scallions,Garlic,Bread,Garlic Powder'),
(52993,'Potatoes,Broccoli,Garlic,Chicken Breast,Balsamic Vinegar,Honey'),
(52996,'Chicken Breasts,Carrots,Potatoes,Onion,Beef Stock,Mozzarella'),
(52997,'Rice,Onion,Lime,Garlic Clove,Cucumber,Carrots'),
(52998,'Beef Brisket,Small Potatoes,Carrots,Cabbage,,'),
(53000,'Potatoes,Small Potatoes,Salted Butter,Mushrooms,Brown Lentils,Garlic'),
(53005,'Flour,Salt,Sugar,Butter,Water,Rhubarb'),
(53006,'Beef,Aubergine,Greek Yogurt,Egg,Parmesan,Tomato'),
(53007,'Digestive Biscuits,Almonds,Butter,Greek Yogurt,Mascarpone,Eggs'),
(53011,'Quinoa,Butter,Red Chilli,Garlic,Chicken Breast,Olive Oil'),
(53012,'Butter Beans,Olive Oil,Onion,Garlic Clove,Tomato Puree,Tomatoes'),
(53013,'Minced Beef,Olive Oil,Sesame Seed Burger Buns,Onion,Iceberg Lettuce,Cheese'),
(53015,'Yeast,Water,Water,Sugar,Salt,Eggs'),
(53016,'Chicken Breast,Pickle Juice,Egg,Milk,Flour,Icing Sugar'),
(53017,'Flour,Salt,Egg,Egg,Butter,Butter'),
(53019,'Butter,Chopped Onion,Sauerkraut,Butter,Chopped Onion,Potatoes'),
(53020,'Chicken Legs,Onions,Carrots,Leek,Celery,Cabbage'),
(53021,'Cabbage,Butter,Onion,Ground Beef,Ground Pork,Rice'),
(53022,'Flour,Eggs,Milk,Water,Salt,Sugar'),
(53024,'Butter,Egg Yolks,Cream Cheese,Baking Powder,Flour,Jam'),
(53025,'Broad Beans,Parsley,Olive Oil,Lemons,Garlic Clove,Cumin'),
(53026,'Broad Beans,Spring Onions,Garlic Clove,Parsley,Cumin,Baking Powder'),
(53027,'Brown Lentils,Rice,Coriander,Macaroni,Chickpeas,Onion'),
(53028,'Chicken Thighs,Coriander,Cumin,Cardamom,Cayenne Pepper,Paprika'),
(53029,'Mulukhiyah,Onion,Beef,Salt,Water,Garlic Clove'),
(53030,'Flour,Water,Salt,Unsalted Butter,Olive Oil,'),
(53031,'Beef,Onion,Chicken Stock Cube,Tomatoes,Garlic Clove,Tomato Puree'),
(53033,'Sushi Rice,Mirin,Pickle Juice,Spring Onions,,'),
(53038,'Potatoes,Milk,Butter,Mustard,Spring Onions,Spring Onions'),
(53039,'Chicken,Red Chilli,Garlic,Ginger,Dried Oregano,Coriander'),
(53042,'Garlic,Beef Fillet,Olive Oil,Vinegar,Parsley,Ciabatta'),
(53046,'Plain Flour,Icing Sugar,Puff Pastry,Caster Sugar,Lemon Zest,Cinnamon'),
(53047,'Carrots,Onion,Garlic Clove,Cumin,Coriander,Olive Oil'),
(53049,'Milk,Oil,Eggs,Flour,Baking Powder,Salt'),
(53050,'Chicken Thighs,Challots,Ginger,Garlic Clove,Cayenne Pepper,Turmeric'),
(53052,'Minced Beef,Onion,Eggs,Chilli,Baguette,Salt'),
(53053,'Beef,Vegetable Oil,Cinnamon Stick,Cloves,Star Anise,Cardamom'),
(53054,'Rice,Coconut Milk,Water,Salt,Corn Flour,Flour'),
(53055,'Minced Beef,Minced Pork,Onion,Garlic,Parsley,Paprika'),
(53056,'Potatoes,Courgettes,Carrots,Green Pepper,Aubergine,Onion'),
(53057,'Beef,Onions,Carrots,Garlic,Bay Leaf,Red Wine'),
(53058,'Cannellini Beans,Vegetable Oil,Tomatoes,Challots,Garlic,Parsley'),
(53059,'Mushrooms,Buckwheat,Vegetable Oil,Onion,Garlic,Bay Leaf'),
(53060,'Filo Pastry,Minced Beef,Onion,Oil,Salt,Pepper'),
(53061,'Sardines,Vegetable Oil,Flour,Salt,,'),
(53062,'Flour,Caster Sugar,Yeast,Salt,Milk,Eggs'),
(53063,'Beef Brisket,Bread,Lettuce,Tomato,Ham,Mozzarella'),
(53064,'Fettuccine,Heavy Cream,Butter,Parmesan,Parsley,Black Pepper'),
(53067,'Green Pepper,Olive Oil,Onion,Garlic,Quinoa,Black Beans'),
(53068,'Garlic,Onion,Beef,Tomato Puree,Water,Olive Oil'),
(53069,'Beef,Soy Sauce,Lemon,Garlic,Onion,Olive Oil'),
(53070,'Beef,Beef Stock,Soy Sauce,Water,Green Pepper,Red Pepper'),
(53071,'Beef,Beef Stock Concentrate,Tomato Puree,Water,Soy Sauce,White Wine Vinegar'),
(53072,'Egg Plants,Breadcrumbs,Sesame Seed,Eggs,Salt,Pepper'),
(53073,'Egg Plants,Sugar,Salt,Pepper,Garlic,Olive Oil'),
(53074,'Egg Plants,Coconut Milk,Lemon Juice,Salt,Red Pepper Flakes,Onions'),
(53075,'Egg Plants,Eggs,Salt,Olive Oil,,'),
(53076,'Bread,Egg,Salt,,,'),
(53077,'Unsalted Butter,Onion,Cabbage,Carrots,Celery,Bay Leaf'),
(53078,'Beetroot,Olive Oil,Chicken Stock Cube,Water,Potatoes,Cannellini Beans'),
(53080,'Buckwheat,Flour,Salt,Yeast,Milk,Butter'),
(53081,'Potatoes,Carrots,Salt,White Wine Vinegar,Eggs,Sausages'),
(53082,'Strawberries,Sugar,Grand Marnier,Cream,Sour Cream,'),
(53085,NULL);